### ISSUE TITLE
如何了解框架构建的原理与编程思路

### ISSUE THREAD

**Issue by zealseeker** [ictxiangxin/paradox#1]
看paradox的代码感觉好轻量级，思路和TensorFlow很像但非常简便，特别适合学习了解框架的构建。

相信对我们这些初学者来说非常有用。

这里想请求作者是否可以分享些关于这些框架的思路或者相关的教程呢，直接看源代码感觉有点摸不着头脑，尤其是engin和symbol两个类。

**Comment by ictxiangxin** [comment]
@zealseeker 你好，我在完成大致框架后会写一份与代码同等规模的文档来详细描述整个系统，我在编写代码时也一直坚持所有单词不用简写的方式来提高可读性，尽量不使用过于复杂的语法糖。

现在人力有限，我之后会尝试边完成代码边添加文档。
